name: ntm_flutter
repository: https://github.com/Novade/ntm_flutter

packages:
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true


scripts:
  format:
    exec: flutter format --set-exit-if-changed .
    description: Run `dart format` in all packages.
  analyze:
    exec: flutter analyze --fatal-infos .
    description: Run `dart analyze` in all packages.
  test:
    exec: flutter test .
    description: Run `dart test` in all packages.
  test-coverage:
    exec: flutter test --coverage .
    description: Run `dart test` in all packages.
  # cSpell:ignore lcov
  format-coverage:
    exec: format_coverage --lcov --in=coverage --out=coverage/coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib
    description: Run `dart test` in all packages.
