// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIi-L2Y7-baGw-UB827iO9wLNGwRkVeuc',
    appId: '1:1089649932579:web:0f490c732933eae08ff496',
    messagingSenderId: '1089649932579',
    projectId: 'ntm-pad',
    authDomain: 'ntm-pad.firebaseapp.com',
    storageBucket: 'ntm-pad.appspot.com',
    measurementId: 'G-QT16KN6LJK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwG1p3szBPyGO7TBtO5L4D2aZjOgzbOmQ',
    appId: '1:1089649932579:ios:e5104f76bdf0e0748ff496',
    messagingSenderId: '1089649932579',
    projectId: 'ntm-pad',
    storageBucket: 'ntm-pad.appspot.com',
    iosClientId:
        '1089649932579-1o897dp2dpdvvftmd78ajhfmurokrihb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ntmPad',
  );
}
